-- Task 2: Register SYSDATE procedure in EBS / Create an Oracle EBS Procedure
CREATE OR REPLACE PROCEDURE ANIL_PR_SYSDT (
    ERRBUF  OUT VARCHAR2,
    RETCODE OUT NUMBER
) IS
    V_DT DATE;
BEGIN
    SELECT SYSDATE INTO V_DT FROM DUAL;

    FND_FILE.PUT_LINE(FND_FILE.LOG, 'YOU CAN SEE LOG DETAILS HERE !');
    FND_FILE.PUT_LINE(FND_FILE.OUTPUT, 'CURRENT DATE = ' || V_DT);

EXCEPTION
    WHEN OTHERS THEN
        FND_FILE.PUT_LINE(FND_FILE.OUTPUT, 'CHECK YOUR PROGRAM: ' || ERRBUF || ' ERRCODE = ' || RETCODE);
END;
/